// Import Screens
import {
  AddPost,
  EditPost,
  GuestDashboard,
  Home,
  Jobs,
  Profile,
  Search,
  ViewJobs,
  Filter,
  ModelProfile,
  IdentityVerification,
  UserDashboard,
  Notifications,
  PostListing,
  SubmitProposal,
  LatestProposal,
  SavedJobDetails,
  FollowDetails,
  ManageAccount,
  PrivacyPolicy,
  TermsOfService,
  ContactUs,
  HelpSupport,
  ManageJobs,
  ManageProposal,
  Checkout,
  PostJob,
  ProjectDetails,
  Invoice,
  OrderCheckout,
  Feedback,
  Settings,
  Chat,
  Inbox,
  PayoutSetting,
  ClientProfile,
  CastingCalls, 
  PackagePayment,
  FeedUserProfile,
  ManagePortfolios,
  ManageSocialPosts,
  EditPostJob,
  ConnectionStatus,
  AddStripAccount,
  EditCastingCalls,
  ManageProjects,
  EditSubmitProposal,
  ModelUserProfile,
  PhotographerProfile,
  PhotographerUserProfile,
  AddPortfolio,
  ViewPostDetails,
  PushNotificationScreen,
  GalleryImages,
  Packages,
  ManageAvailability,
  PayoutHistory,
} from "../../Screens/Others";
import BottomTab from "../../Navigations/BottomTab";

// Screens naming convension
export const otherScreens = {
  Home: Home,
  BottomTab: BottomTab,
  Jobs: Jobs,
  Search: Search,
  Profile: Profile,
  AddPost: AddPost,
  EditPost: EditPost,
  GuestDashboard: GuestDashboard,
  ViewJobs: ViewJobs,
  Filter: Filter,
  ModelProfile: ModelProfile,
  IdentityVerification: IdentityVerification,
  UserDashboard: UserDashboard,
  Packages: Packages,
  Notifications: Notifications,
  PostListing: PostListing,
  SubmitProposal: SubmitProposal,
  LatestProposal: LatestProposal,
  SavedJobDetails: SavedJobDetails,
  FollowDetails: FollowDetails,
  ManageAccount: ManageAccount,
  PrivacyPolicy: PrivacyPolicy,
  TermsOfService: TermsOfService,
  ContactUs: ContactUs,
  HelpSupport: HelpSupport,
  ManageJobs: ManageJobs,
  ManageProposal: ManageProposal,
  Checkout: Checkout,
  PostJob: PostJob,
  ProjectDetails: ProjectDetails,
  Invoice: Invoice,
  OrderCheckout: OrderCheckout,
  Feedback: Feedback,
  Settings: Settings,
  Chat: Chat,
  Inbox: Inbox,
  PayoutSetting: PayoutSetting,
  ClientProfile: ClientProfile,
  CastingCalls: CastingCalls, 
  PackagePayment: PackagePayment,
  FeedUserProfile: FeedUserProfile,
  ManagePortfolios: ManagePortfolios,
  ManageSocialPosts: ManageSocialPosts,
  EditPostJob: EditPostJob,
  ConnectionStatus: ConnectionStatus,
  AddStripAccount: AddStripAccount,
  EditCastingCalls: EditCastingCalls,
  ManageProjects: ManageProjects,
  EditSubmitProposal: EditSubmitProposal,
  ModelUserProfile: ModelUserProfile,
  PhotographerProfile: PhotographerProfile,
  PhotographerUserProfile: PhotographerUserProfile,
  AddPortfolio: AddPortfolio,
  ViewPostDetails: ViewPostDetails,
  PushNotificationScreen: PushNotificationScreen,
  GalleryImages: GalleryImages,
  ManageAvailability: ManageAvailability,
  PayoutHistory: PayoutHistory,
};
