import { Platform } from "react-native";
import { dimensionheight, Colors } from "../Constants";

export const Styles = {
  cardContainer: {
    // flex: 0.5,
    flexDiection: "row",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 25,
    backgroundColor: Colors?.white,
    borderRadius: 25,
    // position: 'relative',
    shadowColor: Colors?.themeColor,
    elevation: 5,
    // width:dimensionWidth('90%'),
    marginTop: Platform?.OS == "android" ? -120 : -110,
    // left:30
    margin: 20,
    shadowOpacity: 0.2,
  },
  shadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5, // Android shadow
  },
  headerContainer: {
    // flex: 0.5,
    height: 340,
    padding: 20,
    paddingTop: Platform?.OS == "android" ? 20 : 50,
    backgroundColor: Colors?.lightThemeColor,
    borderBottomEndRadius: 25,
    borderBottomStartRadius: 25,
    boxSizing: "border-box",
    position: "relative",
    shadowColor: Colors?.black,
    elevation: 5,
    shadowOpacity: 2,
  },
  dashboardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    backgroundColor: Colors?.white,
    borderBottomEndRadius: 20,
    borderBottomStartRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 10,
    shadowColor: Colors?.black,
    elevation: 5,
    paddingTop: Platform?.OS == "android" ? 20 : 50,
    shadowOpacity: 0.2,
  },
  bannerCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
    borderRadius: 15,
    backgroundColor: Colors?.themeColor,
    margin: 15,
    alignItems: "flex-start",
    paddingBottom: 1,
    shadowColor: Colors?.black,
    elevation: 5,
    shadowOpacity: 0.2,
  },
  smallButton: {
    borderRadius: 30,
    backgroundColor: Colors?.white,
    paddingVertical: 5,
    paddingHorizontal: 10,
    // width: "60%",
    alignItems: "center",
    marginVertical: 10,
    paddingBottom: 5.5,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: Colors?.white,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 20,
    marginHorizontal: 20,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: Colors?.themeColor,
    alignItems: "center",
  },
  tabButton: {
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: Colors?.white,
    paddingVertical: 6,
    paddingHorizontal: 20,
    borderRadius: 20,
    width: "50%",
  },
  tabButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    borderWidth: 1,
    borderColor: Colors?.themeColor,
    borderRadius: 20,
  },
  postCard: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: 350,
    width: "100%",
    resizeMode: "contain",
    position: "relative",
    shadowOpacity: 1,
    elevation: 5,
    shadowColor: Colors?.black,
  },
  bottomTextView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
  },
  container: {
    marginTop: 20,
    marginHorizontal: 20,
    borderRadius: 12,
    backgroundColor: Colors?.white,
    width: "90%",
    padding: 15,
    shadowColor: Colors?.black,
    elevation: 5,
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 10 },
  },
  headingView: {
    borderLeftWidth: 4,
    borderColor: Colors?.themeColor,
    backgroundColor: Colors?.white,
    borderRadius: 10,
    marginTop: 10,
    marginHorizontal: 18,
    width: "90%",
  },
  flexRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  separator: {
    borderBottomWidth: 0.5,
    borderColor: Colors?.grey,
    width: "100%",
    marginVertical: 8,
    paddingVertical: 2,
  },
  boxShadow: {
    shadowColor: Colors?.black,
    elevation: 5,
    shadowOpacity: 0.2,
  },
  inputField: {
    width: "100%",
    borderWidth: 1,
    borderColor: Colors?.grey,
    marginVertical: 10,
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  elevation: {
    shadowColor: "#171717",
    elevation: 5,
  },
};
